# Generated by Django 3.0.4 on 2020-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='image_directory/'),
        ),
    ]
